version: '3'

services:

  php:
    container_name: door-logger-php
    user: ${user}
    build: ./php/
    volumes:
        - ../laravel:/var/www/html
    depends_on:
        - db
  nginx:
    image: nginx
    container_name: door-logger-nginx
    ports:
        - 8010:80
    volumes:
        - ../laravel:/var/www/html
        - ./nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php

  db:
    image: mysql:5.7
    container_name: door-logger-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: door-logger-database
      MYSQL_USER: door-logger-docker
      MYSQL_PASSWORD: door-logger-test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3600:3306
