version: '3'

services:

    nginx:    
        build: ./nginx/ssl/
        container_name: "door-logger-nginx"
        ports:
            - "8081:80"
        volumes:
            - ../laravel:/var/www
            - ./door-loggerLogs/nginx:/var/log/nginx/
        depends_on:
            - php
  
    php:
        build: ./php/
        user: ${user}
        container_name: "door-logger-php"
        volumes:
            - ../laravel:/var/www
            - ./door-loggerLogs/php:/var/log/php/
        links:
            - db
        depends_on:
            - db
    
    db:
        build: ./mysql
        container_name: "door-logger-db"
        ports:
            - 3360:3306
        environment:
            MYSQL_DATABASE: door-logger-database
            MYSQL_USER: door-logger-user
            MYSQL_PASSWORD: door-logger-password
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        tty: true

    redis:
        container_name: door-logger-redis
        image: redis:6.0.9
        ports:
          - 6379:6379

    # Echo Server
    laravel-echo-server:
        container_name: door-logger-laravel-echo
        build: ./laravel-echo
        ports:
          - 6001:6001
        volumes:
          - ./laravel-echo/:/work:cached
        working_dir: /work

    node:
        image: node:16
        container_name: door-logger-node
        volumes:
            - ../laravel:/mnt/laravel/
        tty: true